# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DJabberd-Plugin-Balancer
version:      0.1
version_from: lib/DJabberd/Plugin/Balancer.pm
installdirs:  site
requires:
    DJabberd:                      0.83

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
